2024-04-21 19:03:33,747 - INFO - Using 16bit Automatic Mixed Precision (AMP)
2024-04-21 19:03:33,825 - INFO - GPU available: True (cuda), used: True
2024-04-21 19:03:34,042 - INFO - TPU available: False, using: 0 TPU cores
2024-04-21 19:03:34,042 - INFO - IPU available: False, using: 0 IPUs
2024-04-21 19:03:34,042 - INFO - HPU available: False, using: 0 HPUs
2024-04-21 19:03:34,085 - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 4060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-04-21 19:03:35,293 - WARNING - Missing logger folder: result/checkpoint/convnext-b-pretrained
2024-04-21 19:03:35,302 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-21 19:03:35,322 - INFO - 
  | Name  | Type     | Params
-----------------------------------
0 | model | ConvNeXt | 87.6 M
-----------------------------------
87.6 M    Trainable params
0         Non-trainable params
87.6 M    Total params
350.286   Total estimated model params size (MB)
2024-04-21 19:03:56,935 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-21 19:03:59,730 - ERROR - [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
Traceback (most recent call last):
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 407, in <module>
    test_loss, tess_acc, best_epoch = plot_results(interval, model_name, model_option, latest_version, monitor_value)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 214, in plot_results
    log_results = pd.read_csv(f"{result_path}/checkpoint/{interval}/{model_name}-{model_option}/{latest_version}/metrics.csv")
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
