2024-04-22 12:47:53,908 - INFO - Using 16bit Automatic Mixed Precision (AMP)
2024-04-22 12:47:53,970 - INFO - GPU available: True (cuda), used: True
2024-04-22 12:47:54,191 - INFO - TPU available: False, using: 0 TPU cores
2024-04-22 12:47:54,191 - INFO - IPU available: False, using: 0 IPUs
2024-04-22 12:47:54,192 - INFO - HPU available: False, using: 0 HPUs
2024-04-22 12:47:54,225 - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 4060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-04-22 12:47:55,203 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-22 12:47:55,214 - INFO - 
  | Name  | Type     | Params
-----------------------------------
0 | model | ConvNeXt | 87.6 M
-----------------------------------
87.6 M    Trainable params
0         Non-trainable params
87.6 M    Total params
350.286   Total estimated model params size (MB)
2024-04-22 12:48:01,624 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-22 12:48:02,510 - ERROR - [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
Traceback (most recent call last):
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 501, in <module>
    test_loss, tess_acc, best_epoch = plot_results(interval,
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 211, in plot_results
    log_results = pd.read_csv(f"{result_path}/checkpoint/{interval}/{model_name}-{model_option}/{latest_version}/metrics.csv")
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
2024-04-22 12:50:39,731 - INFO - Using 16bit Automatic Mixed Precision (AMP)
2024-04-22 12:50:39,803 - INFO - GPU available: True (cuda), used: True
2024-04-22 12:50:40,030 - INFO - TPU available: False, using: 0 TPU cores
2024-04-22 12:50:40,030 - INFO - IPU available: False, using: 0 IPUs
2024-04-22 12:50:40,030 - INFO - HPU available: False, using: 0 HPUs
2024-04-22 12:50:40,061 - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 4060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-04-22 12:50:40,961 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-22 12:50:41,099 - ERROR - module 'torch.optim' has no attribute 'lr_schedulerCosineAnnealingLR'
Traceback (most recent call last):
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 504, in <module>
    trainer.fit(module)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 963, in _run
    self.strategy.setup(self)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 159, in setup
    self.setup_optimizers(trainer)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 139, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 178, in _init_optimizers_and_lr_schedulers
    optim_conf = call._call_lightning_module_hook(model.trainer, "configure_optimizers", pl_module=model)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 120, in configure_optimizers
    scheduler = torch.optim.lr_schedulerCosineAnnealingLR(optimizer,
AttributeError: module 'torch.optim' has no attribute 'lr_schedulerCosineAnnealingLR'
2024-04-22 12:51:49,952 - INFO - Using 16bit Automatic Mixed Precision (AMP)
2024-04-22 12:51:50,021 - INFO - GPU available: True (cuda), used: True
2024-04-22 12:51:50,269 - INFO - TPU available: False, using: 0 TPU cores
2024-04-22 12:51:50,269 - INFO - IPU available: False, using: 0 IPUs
2024-04-22 12:51:50,269 - INFO - HPU available: False, using: 0 HPUs
2024-04-22 12:51:50,302 - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 4060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-04-22 12:51:51,178 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-22 12:51:51,189 - INFO - 
  | Name  | Type     | Params
-----------------------------------
0 | model | ConvNeXt | 87.6 M
-----------------------------------
87.6 M    Trainable params
0         Non-trainable params
87.6 M    Total params
350.286   Total estimated model params size (MB)
2024-04-22 12:51:57,665 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-22 12:51:58,347 - ERROR - [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
Traceback (most recent call last):
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 517, in <module>
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 227, in plot_results
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'result/checkpoint/7200/convnext-b-pretrained/version_0/metrics.csv'
